### ISSUE TITLE
📝 Documentation: Update Documentation

### ISSUE THREAD

**Issue by kumarankit999** [OpenContributionsProject/opencontributionssite#104]
### Bug Report Checklist

- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/OpenContributionsProject/opencontributionssite/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

Documentation of the Readme should be Updated, as their is not Section of Installation, Notes, Information about this Project.

![image](https://github.com/OpenContributionsProject/opencontributionssite/assets/111564362/6e7a6b51-4291-4098-946b-bda61074ec82)

**Comment by JoshuaKGoldberg** [comment]
🤔 There's a link to a _DEVELOPMENT.md_ file on the README.md right now. What specific other information are you looking for?

**Comment by CBID2** [comment]
Hi @JoshuaKGoldberg! :) Maybe there could be a section that mentions where companies can contact others for questions. Or a section that mentions the maintainers of the project. Some thing to think about.

**Comment by JoshuaKGoldberg** [comment]
> where companies can contact others for questions

What kinds of questions are you thinking about?

> section that mentions the maintainers of the project

You mean like the _Contributors_ table? 😄 

We will have an _About Us_ kind of page eventually (#20).

**Comment by CBID2** [comment]
> > where companies can contact others for questions
> 
> What kinds of questions are you thinking about?
> 
> > section that mentions the maintainers of the project
> 
> You mean like the _Contributors_ table? 😄
> 
> We will have an _About Us_ kind of page eventually (#20).

As far as questions, maybe...where they can contact you and Rizel? 
Well, I feel like Maintainers are in a different role as Contributors, so having that distinction could help.

**Comment by JoshuaKGoldberg** [comment]
I thought about this a bit - I think having issue forms on the repo is what we'd want to stick with for contacting us. We maintainers both have public personas that indicate how to talk to us; any new maintainer that doesn't have that probably indicates they don't want to be reached out to.

Closing this issue for now - but if there's anything specific you'd want to have documented, please do file a new issue! (and, tip, give it a title specific to the request - "update documentation" is a bit vague)
