### ISSUE TITLE
🛠 Tooling: Switch to Next.js app router

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [OpenContributionsProject/opencontributionssite#112]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/OpenContributionsProject/opencontributionssite/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

This repo is set up with [Next.js `pages/`](https://nextjs.org/docs/pages/building-your-application/routing/pages-and-layouts). Which is the classic/traditional way of doing app pages in Next.js.

But Next.js has a shiny new way of doing things now! [Next.js `app/` routing](https://nextjs.org/docs/app/building-your-application/routing/pages-and-layouts) is awesome and a better way to do things.

Let's migrate this project do `app/`!

**Comment by kevinzunigacuellar** [comment]
Is it too late to suggest Astro as the website framework 👀? (asking for a friend 😆)

**Comment by JoshuaKGoldberg** [comment]
Haha sorry @kevinzunigacuellar, yes it is 😜

**Comment by kevinzunigacuellar** [comment]
.take
