### ISSUE TITLE
📝 Documentation: Add a quickstart on GitHub Codespaces

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [OpenContributionsProject/opencontributionssite#16]
### Bug Report Checklist

- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/OpenContributionsProject/opencontributionssite/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

Forking from https://github.com/OpenContributionsProject/opencontributionssite/pull/4#discussion_r1054987694: we have a `.github/DEVELOPMENT.md` file that describes how to get started locally, but no docs on how to get started with [GitHub Codespaces](https://github.com/features/codespaces). It'd be nice to:

1. [Set up this repository for GitHub Codespaces](https://docs.github.com/en/codespaces/setting-up-your-project-for-codespaces)
2. Document how to use the codespaces in `.github/DEVELOPMENT.md`

**Comment by blackgirlbytes** [comment]
Setting up pnpm in GitHub Codespaces is different than I'm used to, so I'm going to get advice from the Codespaces team. Need to do some research first.
