### ISSUE TITLE
📝 Documentation: There is no contributing.md file

### ISSUE THREAD

**Issue by dev-phantom** [OpenContributionsProject/opencontributionssite#18]
### Bug Report Checklist

- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/OpenContributionsProject/opencontributionssite/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

I would love to contribute to this  repo but i realized there is no `contributing.md` file 
i

**Comment by JoshuaKGoldberg** [comment]
Hey @dev-phantom, thanks for looking into contributing! We do have a contributing.md file actually: https://github.com/OpenContributionsProject/opencontributionssite/blob/d787e75b650bc3059b075c2468a848ebaa2cc2b4/.github/CONTRIBUTING.md

Per [Setting guidelines for repository contributors](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors), `.github/CONTRIBUTING.md` is a valid place for it.
