### ISSUE TITLE
Create logo for open source contributions project

### ISSUE THREAD

**Issue by blackgirlbytes** [OpenContributionsProject/opencontributionssite#2]
The open source contributions project is made to help encourage companies to support open source projects through finances, time, and effort. We want a logo that captures that essence.

Here are a few logos that other projects that have a similar mission for inspiration
![image](https://user-images.githubusercontent.com/77015356/208575371-e7dbd097-32c4-4227-93bd-32ee48373b47.png)
![image](https://user-images.githubusercontent.com/77015356/208575479-aec96b1a-8248-40ff-be40-a4323e5f8711.png)
![image](https://user-images.githubusercontent.com/77015356/208575789-0ff2dad7-14d0-4676-873d-7525682c72f3.png)
![image](https://user-images.githubusercontent.com/77015356/208575907-70365a78-997b-4279-a332-62f6341a15d6.png)
![image](https://user-images.githubusercontent.com/22990146/208577460-2a20bbb8-12b1-4c53-a8e0-855be46c5a9b.png)

**Comment by scribblndibbl** [comment]
HI Rizel, as agreed I'll take this issue.

**Comment by iamkingsleey** [comment]
Okay, Thank you @blackgirlbytes

**Comment by iamkingsleey** [comment]
Please let me know your thoughts about the designs when you are available.

![1](https://user-images.githubusercontent.com/63562509/212495063-5258b23a-d14e-47cd-8a8e-fd2e48a85865.jpg)
![2](https://user-images.githubusercontent.com/63562509/212495105-3d44cf5a-575a-4ec2-82af-0271fda343b1.jpg)
![3](https://user-images.githubusercontent.com/63562509/212495122-f2009d43-43aa-4f48-8a7f-d47a7b4acc9f.jpg)

**Comment by blackgirlbytes** [comment]
@iamkingsleey I kinda like the cat with money sign and then my second favorite is the puzzle.

Do you have any thoughts on this @JoshuaKGoldberg?

**Comment by blackgirlbytes** [comment]
Oh wait, I just remembered that @JoshuaKGoldberg told me open source contributions was redundant and the name of the project will be Open Contributions. Could you remove the word source in the logos @iamkingsleey ? Besides that, I love it!

**Comment by iamkingsleey** [comment]
I personally had reservations about the name it sounded generic to me. Great idea @JoshuaKGoldberg.
Thank you @blackgirlbytes for the feedback. I will make the updates ASAP!

**Comment by JoshuaKGoldberg** [comment]
Ah love to see this come in! +1 on the name change. I've been thinking of the name as **Open Contributions Project** - but if there's a better option that'd be great!

And, these logos all are snazzy - thanks for working on them!

A few assorted thoughts...
* Love the font family & typography in all of them, especially the savings box. What's its name? 😄 
* 2/3 of these involve money: and while that's a large part of the mission, _knowledge sharing_ is arguably an even bigger part of it right now. Getting companies to donate money _and time_ is almost a byproduct of them knowing why they should. I'd love to see more explorations around the area of knowledge sharing / community activism / etc.
    * I also wonder if including the American dollar sign limits the perceived applicability of the project to just US folks?
* I didn't get 'cat' from the cat one, actually more a flower. Which is kind of nice too? I like that accidental interpretation too.
    * I also wouldn't want us to be seen as specific to GitHub: we'd be applicable to any other project hosting site, e.g. Gitlab.

What do you two think @blackgirlbytes @iamkingsleey?

**Comment by iamkingsleey** [comment]
Wow, insightful feedback. Based on the initial brief I felt it was more about helping raise funds for open-source projects like "Open Source Collective" Never thought about knowledge sharing... I will make some more exploration and share.
Thank you @JoshuaKGoldberg

**Comment by blackgirlbytes** [comment]
@JoshuaKGoldberg I agree that the cat..might be too specific to GitHub. But I looove the octocat LOL. 

Actually, your comment makes me wonder more about the initial brief leading you to believe that it's more about raising funds @iamkingsleey. I would love to know more. I think I pointed you to the project goals [here](https://github.com/OpenContributionsProject). Does the README give the impression that it's more about funds? I ask because if so, I'll make a PR to add clarity. OR are you talking about the conversation I had with you where I said, "the general idea is to help companies understand how they can support and contribute to open source projects." If so, I'll be more clear when speaking to other folks. Just curious on my end on how to add clarity for the future! Thanks!

**Comment by iamkingsleey** [comment]
Okay, I guess I took our initial chat too seriously... Lol,
Thank you @blackgirlbytes. I will share more concepts soon.

**Comment by blackgirlbytes** [comment]
@iamkingsleey looking forward to it! I appreciate your work so far! And this is good feedback for me..I will be more clear with others in the future!

**Comment by JoshuaKGoldberg** [comment]
+1 on appreciating the work so far - I'm really excited to see what's next! 😍 ❤️‍🔥

**Comment by iamkingsleey** [comment]
Hello Everyone, Hope you'all had a great weekend. 
what are your thoughts on this?

![Logo-Design-Update](https://user-images.githubusercontent.com/63562509/213997899-f0e2509e-f81e-4fcb-b2e2-3e4243ef1b18.png)

**Comment by JoshuaKGoldberg** [comment]
Ooh! I think I like the first logo the most. There's something very clean about it, but it's not too simple. The design is very catchy and I think would work great as a favicon up. The "open box" concept is nifty too.

My only critique of it would be that it's pretty abstract - it almost feels more related to a [beyblade](https://www.google.com/search?sxsrf=AJOqlzW31TS5PP9LFjBjBqjp2eG4ILzGiQ:1674693810739&q=beyblade&tbm=isch&sa=X&ved=2ahUKEwjY_MjNgOT8AhUAFmIAHUuDBIwQ0pQJegQIDRAB&biw=1470&bih=783&dpr=2#imgrc=zRJaV7VfcxFQCM) situation than open source software. It'd be lovely to see variations of it, to try to make the "open box" / giving / open source connection stronger.

**Comment by blackgirlbytes** [comment]
I like the first two logos the most. The first is my favorite and the second is my second favorite. The last one I'm less of a fan of. The colors pop best in the first one, and I love the open box concept. I personally love that it's abstract, but happy to see more variations if possible.

**Comment by iamkingsleey** [comment]
Okay, Great feedback Team!
I will share more variations soon

**Comment by iamkingsleey** [comment]
I made some slight adjustments to the first one. I was too excited and wanted to try my hand at creating some media templates. By the way, the element (which resembles a connectivity fiber) in the middle of the box symbolizes connection and networking. When an individual is properly connected or networks with the right people, they are bound to learn, and I believe these are key to what we aim to achieve with the Open Contribution/Collaboration Project.

![1](https://user-images.githubusercontent.com/63562509/216301616-d0be28cb-d349-468a-a39e-703af362dfdc.jpg)
![2](https://user-images.githubusercontent.com/63562509/216301635-280828cb-74d3-4db9-b57d-a2b44c9f61f4.jpg)
![3](https://user-images.githubusercontent.com/63562509/216301657-5ef17568-0ebf-4718-aeaa-571360fdaefa.jpg)
![4](https://user-images.githubusercontent.com/63562509/216301674-44f4ce84-88bd-47d9-b766-c70d35866a38.jpg)
![5](https://user-images.githubusercontent.com/63562509/216301697-e5d3a65a-60fe-4228-9d32-61de43be4d9e.jpg)

**Comment by blackgirlbytes** [comment]
I like the variation in colors especially these two: 
<img width="289" alt="Screen Shot 2023-02-07 at 8 30 19 PM" src="https://user-images.githubusercontent.com/22990146/217405465-b35f6923-3a0e-4261-83bd-072916e60b11.png">
<img width="264" alt="Screen Shot 2023-02-07 at 8 30 50 PM" src="https://user-images.githubusercontent.com/22990146/217405582-406dbd3d-e91d-4196-9ab1-a7c25c346174.png">

**Comment by iamkingsleey** [comment]
Thank you @blackgirlbytes

**Comment by blackgirlbytes** [comment]
@JoshuaKGoldberg what do you think?

**Comment by JoshuaKGoldberg** [comment]
Heh, I'm torn on this. The first logo variant from two weeks ago is simpler and I kind of like more. This new one is very good too, but is a bit more complex (and almost reminds me of the 🦠 microbe emoji).

How much time do you have to spare for us @iamkingsleey? If this were a corporate gig I would ask for a bunch of variations in different sub-directions. But you've been so kind to use with these logos. I'm down to just go with the first one. I'm liking it more and more each time I see it. 😄 

![Screenshot of the OCP logo from 2 weeks ago (filled in center square)](https://user-images.githubusercontent.com/3335181/217614423-3cd61f96-88fb-496c-8462-ffa51a920ea3.png)

The colors and typography from this most recent batch are 💯. I have no notes. Just appreciation and excitement!

**Comment by blackgirlbytes** [comment]
So, sounds like we might choose this icon 
![image](https://user-images.githubusercontent.com/22990146/218152905-0c7a3bc5-9263-4225-8552-6dd3a0418563.png)
but with the color variations from this batch https://github.com/OpenContributionsProject/opencontributionssite/issues/2#issuecomment-1413538755

**Comment by iamkingsleey** [comment]
Okay great @blackgirlbytes 
Something interesting happened. I was invited to speak on "Design and Open-Source". While looking up videos about open-source as I prepped for the session; I bumped into this. 
![Group 34185](https://user-images.githubusercontent.com/63562509/218989612-c1446ba8-c3b8-478f-b498-697097689583.png)
I was totally unaware of this when I created the mark. But it does feel great to know that there is a deeper meaning to this than I thought.

**Comment by iamkingsleey** [comment]
Here are the color variants. I will export the different logo formats and share the drive link here if we are gamed with this concept.

![OCP Logo Design-10](https://user-images.githubusercontent.com/63562509/218991626-a0ff2a2f-f209-4424-aca4-98e741327afc.jpg)

**Comment by blackgirlbytes** [comment]
I'm game! Thank you so much @iamkingsleey !!!!!

**Comment by JoshuaKGoldberg** [comment]
+1, this is fantastic! 🙌

**Comment by JoshuaKGoldberg** [comment]
🚀 thanks so much @iamkingsleey! I'll go ahead and mark this issue as resolved.

**Comment by JoshuaKGoldberg** [comment]
@allcontributors add @iamkingsleey for design

**Comment by JoshuaKGoldberg** [comment]
Btw, uploading this zip just in case: 
[drive-download-20230512T231717Z-001.zip](https://github.com/OpenContributionsProject/opencontributionssite/files/11468284/drive-download-20230512T231717Z-001.zip)
