### ISSUE TITLE
🚀 Feature: Add an "explainer" page for what open source is for non-developers

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [OpenContributionsProject/opencontributionssite#22]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/OpenContributionsProject/opencontributionssite/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

Open source needs to be explained to many people, not just software developers. That includes folks working in finance, marketing, operations, and other areas.

We'll want a page that explains open source for non-developers in the context of the Open Contributions Project:

* What open source means, broadly
* Why projects choose to be open source
* Why companies often choose to consume open source
* Why companies often choose to publish open source

### Additional Info

Per #20, we'll eventually have a full design for the site & menus. But for now this page can live on its own.

This site is built on [Next.js](https://nextjs.org). You can create a new page by adding a `.md` file under `src/pages`. See https://nextjs.org/docs/basic-features/pages.

**Comment by CBID2** [comment]
.doctake

**Comment by blackgirlbytes** [comment]
Thank you @CBID2 !!!!

**Comment by CBID2** [comment]
> Thank you @CBID2 !!!!

Just finished the [PR](https://github.com/OpenContributionsProject/opencontributionssite/pull/101) @blackgirlbytes! :) Thank you so much for sharing this project with me! :)
