### ISSUE TITLE
📝 Documentation: Add mention of the Take action to the Contributing guide

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [OpenContributionsProject/opencontributionssite#50]
### Bug Report Checklist

- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/OpenContributionsProject/opencontributionssite/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

#7 added usage of [bdougie/take-action](https://github.com/bdougie/take-action), which allows people to assign an issue to themselves. But it's not documented in this repo's `.github/CONTRIBUTING.md`. Let's add a mention in some way?

**Comment by blackgirlbytes** [comment]
.take
